services:
  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    build:
      context: / # Use an image built from the specified dockerfile in the directory.
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    depends_on:
      - postgres # This service depends on postgres. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: ${DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USER}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_USER}
      - POSTGRES_USER=${DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - backend

# Networks to be created to facilitate communication between containers
networks:
  backend: